name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install Dependencies
        run: |
          npm ci
          npm run build
      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting --token "${FIREBASE_TOKEN}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
